### ISSUE TITLE
Add abstract factory pattern

### ISSUE THREAD

**Issue by Madman10K** [Neyko641/Design-Patterns#4]
The abstract factory pattern is a common design pattern that is similar to the factory pattern but is used quite differently. Rather than having a factory function for every platform as an example, we can create a class that handles creation of instances based on the given platform. Example below:

If we have a UI element with a different font based on the underlying OS we can use the abstract factory pattern to abstract checking for the platform and rendering the correct font. This means that the developer who uses you GUI library compiles with the same function call and doesn't notice a thing even though you create the element with a whole different class and font

**Comment by Madman10K** [comment]
I will submit a PR about this issue btw :), also forgot to mention that this issue was mentioned and assigned in #2

**Comment by silver-saint** [comment]
Due to some bug this needs to be readded and merged with main.

**Comment by Madman10K** [comment]
Oh yeah I found it, fix will be submitted soon
