### ISSUE TITLE
Add adapter design pattern

### ISSUE THREAD

**Issue by Madman10K** [Neyko641/Design-Patterns#6]
The adapter design pattern is a function or a class specifically made to safely convert information of a type into another for compatibility reasons for example:

OpenGL's coordinate system is not compatible with Vulkan's so if you are developing a cross platform game engine you are going to need to use an adapter function to convert between the two. OpenGL's system is like this (x, y, z), compared to OpenGL, Vulkan's is like this(x, -y, z)

I will submit a PR for this issue :)

**Comment by silver-saint** [comment]
Merge was unsuccessful be careful!

**Comment by Madman10K** [comment]
Ye will submit a fix
